#!/usr/bin/env bash

python ~/OSM/bulk_upload_06/bulk_upload_sax.py \
    --changeset-limit 5000 \
    --put-limit 500 \
    -i ~/OSM/ogr2osm-lukr-import/gonguleidir_LUKR_170910.osm \
    -u "nifgraup@gmail.com" \
    -p "$lukr_pass" \
    -c "Importing data dump of walking routes in Reykjavik donated by LUKR, the city GIS department" \
    -t source=lukr \
    -t details="http://www.openstreetmap.org/user/Ævar%20Arnfjörð%20Bjarmason/diary/11710" \
    -t permission="http://github.com/avar/lukr-osm-donation-2010-09-18/raw/master/Scan.TIF" \
    -t raw_data="http://github.com/avar/lukr-osm-donation-2010-09-18" \
    -t conversion_script="http://github.com/nifgraup/lukr-import"
