#!/usr/bin/perl
#use Modern::Perl;

chomp(my $id_count = qx[cat ~/OSM/ogr2osm-lukr-import/gonguleidir_LUKR_170910.osm | perl -pe 's/.*?id=.(-\\d+).*/\$1/g'|grep ^-|sort|uniq|wc -l]);
chomp(my $import_count = qx[python ~/OSM/bulk_upload_06/util/dump_shelve.py ~/OSM/ogr2osm-lukr-import/gonguleidir_LUKR_170910.osm.db | perl -pe 's/:.*//'|wc -l]);

say "$import_count of $id_count imported or " . ($import_count / $id_count * 100) . "%";
